version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DEBUG: "True"
      SECRET_KEY: change-in-production
      DB_HOST: db
      DB_PORT: "5432"
      DB_NAME: krypt
      DB_USER: krypt
      DB_PASSWORD: krypt_secret
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: krypt_minio
      MINIO_SECRET_KEY: krypt_minio_secret
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - minio

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
