# Generated by Django 5.1.4 on 2026-07-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_escrow_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='escrowed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='payout_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING_AML', 'En attente scoring AML'), ('AML_BLOCKED', 'Bloqué par AML'), ('AML_PENDING_REVIEW', 'Révision AML requise'), ('PROCESSING', 'Paiement en cours'), ('ESCROWED', 'Fonds sécurisés (escrow)'), ('ESCROW_FAILED', 'Échec verrouillage escrow'), ('DELIVERED', 'Livré'), ('PAYMENT_FAILED', 'Paiement échoué'), ('PAYOUT_FAILED', 'Échec payout mobile money')], default='DRAFT', max_length=24),
        ),
    ]
