# Generated by Django 5.1.4 on 2026-07-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0003_transactionmodel_escrowed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING_AML', 'En attente scoring AML'), ('AML_BLOCKED', 'Bloqué par AML'), ('AML_PENDING_REVIEW', 'Révision AML requise'), ('PROCESSING', 'Paiement en cours'), ('ESCROWED', 'Fonds sécurisés (escrow)'), ('ESCROW_FAILED', 'Échec verrouillage escrow'), ('DELIVERED', 'Livré'), ('PAYMENT_FAILED', 'Paiement échoué'), ('PAYOUT_FAILED', 'Échec payout mobile money'), ('CANCELLED', 'Annulé')], default='DRAFT', max_length=24),
        ),
    ]
