# Generated by Django 5.1.4 on 2026-07-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0004_alter_transactionmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='admin_review_tx_hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING_AML', 'En attente scoring AML'), ('AML_BLOCKED', 'Bloqué par AML'), ('AML_PENDING_REVIEW', 'Révision AML requise'), ('PROCESSING', 'Paiement en cours'), ('ESCROWED', 'Fonds sécurisés (escrow)'), ('ESCROW_FAILED', 'Échec verrouillage escrow'), ('DELIVERED', 'Livré'), ('PAYMENT_FAILED', 'Paiement échoué'), ('PAYOUT_FAILED', 'Échec payout mobile money'), ('CANCELLED', 'Annulé'), ('AWAITING_DOCS', 'Documents complémentaires requis'), ('ESCALATED', 'Escaladé (revue niveau 2)')], default='DRAFT', max_length=24),
        ),
    ]
