# Generated by Django 5.1.4 on 2026-08-19 06:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0005_transactionmodel_admin_review_tx_hash_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedBeneficiaryModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('beneficiary_name', models.CharField(max_length=200)),
                ('beneficiary_country', models.CharField(max_length=2)),
                ('momo_number', models.CharField(max_length=30)),
                ('operator', models.CharField(choices=[('MTN_MOMO', 'MTN Mobile Money'), ('ORANGE_MONEY', 'Orange Money')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_beneficiaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transfer_saved_beneficiaries',
                'ordering': ['-created_at'],
            },
        ),
    ]
