# Generated by Django 5.1.4 on 2026-07-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_add_2fa_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_frozen',
            field=models.BooleanField(default=False),
        ),
    ]
