# Generated by Django 5.1.4 on 2026-07-05 06:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0004_add_aml_result'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='amlresultmodel',
            name='is_new_beneficiary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amlresultmodel',
            name='sender_tx_count_30d',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='amlresultmodel',
            name='tag_ml_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='amlresultmodel',
            name='triggered_rules',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='AuditQueueModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transfer_id', models.CharField(db_index=True, max_length=100)),
                ('aml_result_id', models.CharField(max_length=100)),
                ('tag_ml_score', models.FloatField(default=0.0)),
                ('reviewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aml_audit_queue_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_audit_queue',
                'ordering': ['-created_at'],
            },
        ),
    ]
