# Generated by Django 5.1.4 on 2026-07-11 14:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0005_aml_decision_layers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AMLSupportingDocumentModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(db_index=True, max_length=100)),
                ('file_path', models.CharField(max_length=500)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'compliance_aml_supporting_documents',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AlterField(
            model_name='amlresultmodel',
            name='combined_decision',
            field=models.CharField(choices=[('HARD_BLOCK', 'Blocage OFAC/EU'), ('AUTO_APPROVED', 'Approuvé automatiquement'), ('AUTO_BLOCKED', 'Bloqué automatiquement'), ('PENDING_REVIEW', 'Révision admin requise'), ('MANUALLY_APPROVED', 'Approuvé manuellement'), ('MANUALLY_REJECTED', 'Rejeté manuellement'), ('ESCALATED', 'Escaladé (revue niveau 2)')], max_length=20),
        ),
        migrations.CreateModel(
            name='AMLAdminAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(db_index=True, max_length=100)),
                ('action', models.CharField(choices=[('REQUEST_DOCS', 'Documents complémentaires demandés'), ('APPROVE', 'Approuvé (1er niveau)'), ('REJECT', 'Rejeté (1er niveau)'), ('ESCALATE', 'Escaladé'), ('ESCALATED_APPROVE', 'Approuvé (2e niveau)'), ('ESCALATED_REJECT', 'Rejeté (2e niveau)')], max_length=24)),
                ('motif', models.TextField(blank=True, default='')),
                ('tx_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aml_admin_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_aml_admin_audit_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
