# Generated by Django 5.1.4 on 2026-07-11 18:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0006_amlsupportingdocumentmodel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='amladminauditlog',
            name='action',
            field=models.CharField(choices=[('REQUEST_DOCS', 'Documents complémentaires demandés'), ('APPROVE', 'Approuvé (1er niveau)'), ('REJECT', 'Rejeté (1er niveau)'), ('ESCALATE', 'Escaladé'), ('ESCALATED_APPROVE', 'Approuvé (2e niveau)'), ('ESCALATED_REJECT', 'Rejeté (2e niveau)'), ('DOCUMENT', 'Cas documenté'), ('FREEZE_ACCOUNT', 'Compte gelé'), ('TRACFIN_REPORT_GENERATED', 'Déclaration TRACFIN générée')], max_length=24),
        ),
        migrations.CreateModel(
            name='TracfinReportModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(db_index=True, max_length=100)),
                ('file_path', models.CharField(max_length=500)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_tracfin_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_tracfin_reports',
                'ordering': ['-generated_at'],
            },
        ),
    ]
