# Generated by Django 5.1.4 on 2026-07-12 00:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0007_alter_amladminauditlog_action_tracfinreportmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyComplianceReportModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_date', models.DateField(db_index=True, unique=True)),
                ('counts', models.JSONField(default=dict)),
                ('decisions', models.JSONField(default=list)),
                ('polygon_batch_id', models.CharField(blank=True, max_length=100, null=True)),
                ('polygon_batch_tx_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('archived_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_daily_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_daily_reports',
                'ordering': ['-report_date'],
            },
        ),
    ]
