# Generated by Django 5.1.4 on 2026-07-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingaudithash',
            name='batch_tx_hash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pendingaudithash',
            name='event_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='pendingaudithash',
            name='merkle_proof',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
